### ISSUE TITLE
Unhandled Exception Error on Launch

### ISSUE THREAD

**Issue by dhmolson1** [Yoyolick/Boneworks-Save-Manager#3]
**Describe the bug**
Upon launching the program, a 'Microsoft .NET Framework' window pops up saying "Unahandled exception has occured in your application. If you click continue, the app will ignore this error and attempt to continue"..."The remote server returned an error: (404) Not Found"

When I click on 'Details' it displays the following:
"See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at BSM.Form1.ValidateFileSystem()
   at BSM.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BSM
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/dhmol/OneDrive/Desktop/VR%20Tools/BSM.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box."

**To Reproduce**
1. Download BSM
2. Open .exe
3. Window pops up, hit "run anyway"
4. Another window pops up for administrative privileges, press yes
5. See error described above

**Expected behavior**
I expected the application to open normally and look like it does in the demo/troubleshooting Youtube video on the wiki

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera GX

**Comment by dhmolson1** [comment]
Additionally, if I press "Continue" and ignore the error, BSM will not recognize my save location. I cannot Save to Profile, and get the error "Can't find save profile data". I am 100% certain I have selected the folder where my Boneworks .exe is located in my steamapps folder.

**Comment by zoogies** [comment]
Thanks for bringing this to my attention.
I was surprised to see an issue on this repo since I assumed nobody used BSM nowadays.

I can certainly release a new patch to fix your issues, as the first error you've reported is due to me changing my GitHub username recently and breaking the download URLs that BSM looks for when starting.

As for your second issue, It's hard to say whether that is a symptom of the first issue or a different problem entirely.

I will make a new build to fix the 404 shortly; if that does not fix your second problem, we can go from there.

**Comment by zoogies** [comment]
Hey, I've just released a [bugfix release](https://github.com/zoogies/Boneworks-Save-Manager/releases/tag/v1.3).

I would recommend:
1. Going into steamapps and backing up your current save manually, just in case BSM destroys it
2. Deleting `C:\Users\YOURUSERNAME\Documents\BSM` (or /OneDrive/Documents/BSM)
3. Downloading the new 1.3 release
4. Running it, and if you encounter any issues, relaunch the app and try again (since I had error messages that went away after I relaunched during my testing)

I'm going to go ahead and close this issue for now, but if you still have issues after this update please dont hesitate to either reopen this issue, or create a new issue.

Thanks for using BSM!

edit:
Also, make sure you click the `update` button after typing in your path, otherwise it will not work.

**Comment by dhmolson1** [comment]
Thanks a bunch! I was under the impression that Boneworks had cloud saves on Steam, and was getting ready to set up a new game on Boneworks for my friend on my laptop (I usually play on my desktop), so I had assumed that when I downloaded Boneworks on my laptop, my save data from desktop would be there already for me to create a profile from. I imagine that is why I was getting the error regarding not finding the save profile data; because no data had been created on this computer since the game hadn't been launched yet.
